[package]
name = "napi-ffi-bench"
version = "1.0.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
napi-build = "2.1.0"

[dependencies]
napi = { version = "2", default-features = false, features = ["napi4"] }
napi-derive = "2"